# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.10
  - repo:
      https://github.com/charliermarsh/ruff-pre-commit
      # Ruff version.
    rev: "v0.0.265"
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        files: '\.(jsx?|tsx?|css)$'
        additional_dependencies:
        - prettier@2.8.8
#-   repo: local
#    hooks:
#    -   id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [python]
#        args:
#          [
#            "-rn", # Only display messages
#            "-sn", # Don't display the score
#          ]
